name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ['26.5.0']

    steps:
    - name: Checkout code
      uses: actions/checkout@v7

    - name: Set up Node.js
      uses: actions/setup-node@v7
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npx --yes npm@12.0.1 ci

    - name: Run tests
      run: npm test
